const imageSize = '1000x1000'
export default [
  {
    course: 'user interface design & development',
    description: '你可知在那磚瓦碑碣之下，纏繞著什麼樣的歷史故事？透過解謎遊戲讓玩家在層層抽絲剝繭中，實地踏溯不同路線，深入瞭解台南的歷史人文，並享受與夥伴共同解開謎團的樂趣。',
    english_descroption: '“The past is never dead. It’s not even past.” Start on a journey with your partners, and solve the tangled mysteries hidden in Tainan. You can see different sides of Tainan through the story in each stage. By the end, you will figure out a world you’ve never seen before.',
    image: './bg/tangled.jpg',
    members: ['黃筠倫', '蔡宗翰', '劉孟勳', '陳柏佑', '陳柔慈', '陳家年', '邱致揚'],
    semester: 'spring',
    title: '南．纏',
    url: 'http://merry.ee.ncku.edu.tw/uidd2018/Tangled/',
    year: 2018,
  },
  {
    course: 'user interface design & development',
    description: '一起吃飯吧帶你踏上探訪台南私房老店的旅途，隨機配對的功能讓你在旅途中認識新朋友，貼心的話題集功能，第一次見面也不尷尬，PK的歷史小遊戲讓你用趣味的方式更認識台南！',
    english_description: 'Let\'s Eat Together takes you on a trip to visit the old private restuarants in Tainan. The random matching function allows you to meet new friends on the go. Intimate topic set design helps ease the atmosphere of the first encounter. Builtin historical game provides you an interesting way to know more about Tainan!',
    image: './bg/eat-together.jpg',
    image: `https://source.unsplash.com/collection/201/${imageSize}`,
    members: ['陳姵君', '張恩維', '龍淑君', '江佳龍', '王氏', '王喬韋', '黃家蓉', '余宥達'],
    semester: 'spring',
    title: '一起吃飯吧',
    url: 'http://merry.ee.ncku.edu.tw/uidd2018/EatTogether/',
    year: 2018,
  },
  {
    course: 'user interface design & development',
    description: '以成大歷史為背景，築構幽默的故事。想像你在 1930 年代佔領榕樹，50 年後國泰來找你合作，系上因而獲得意外經費，亦或你去殖民其他科系，冠名他們，創造歷史系機械組的快感，這一切，只為了讓你，會心一笑。',
    english_description: 'The humorous stories are created by the history of National Cheng Kung University. Imagine you occupied the Banyan in 1930s. After 50 years, Cathay United Bank Company wants to cooperate with your department. Or, you colonize other departments and you put the title of your department in front of the other, named “Department of History Mechanical Engineering”. Enjoy the excitement of winning!',
    image: './bg/ncku-1971.jpg',
    image: `https://source.unsplash.com/collection/202/${imageSize}`,
    members: ['吳育丞', '張鈞任', '郭泰德', '謝宜憲', '林凱尉', '陳泓名', '蔡淑玲'],
    semester: 'spring',
    title: 'NCKU 1971',
    url: 'http://merry.ee.ncku.edu.tw/uidd2018/NCKU1971/',
    year: 2018,
  },
  {
    course: 'user interface design & development',
    description: '步行台南能夠讓使用者在旅遊台南時，以步行及蒐集當地故事的方式認識並且更貼近台南這塊土地。並在旅途中認識更多的夥伴，一同遊玩增添旅行樂趣。',
    english_description: 'When users use WALKING TAINAN to travel in Tainan, they can know Tainan more deeply through walking and collecting local stories. Users can also meet more and more friends and they can company with each other in this travel. WALKING TAINAN let your travel be full of joy.',
    image: './bg/walking-tainan.jpg',
    imageFocusX: 'right',
    members: ['蘇芊茵', '黃家輝', '郭憶璇', '戴宇', '謝旻恩', '王昱淦'],
    semester: 'spring',
    title: '步行台南',
    url: 'http://merry.ee.ncku.edu.tw/uidd2018/WalkingTainan/',
    year: 2018,
  },
  {
    course: 'web programming',
    description: '我們是一群熱愛中國傳統文化的大學生，深深感受到中國文化之博大精深。有感於風水貴為中國文化的代表性特色，卻無法在日常生活中便利應用，我們決定開發一個簡單的工具，讓大家可以隨時查看地處週遭的風水，發揚中國傳統文化！',
    english_description: 'We are a group of college students into the traditional Chinese culture. Immersed in the beauty of Chinese culture, we deeply realize its prowess. Nonetheless, as a characteristic feature of Chinese culture, Feng Shui is now still not availible in daily life. Therefore, decision was made by us to develop a simple app making it possible for people to look over the Feng Shui of their surroundings by an easy click anytime and anywhere!',
    image: './bg/linguota.jpg',
    image: `https://source.unsplash.com/collection/203/${imageSize}`,
    members: ['陳田原', '林寰鐸', '陳思妤', '游凱為', '莊鎮維'],
    semester: 'fall',
    title: 'Lingouta',
    url: 'http://merry.ee.ncku.edu.tw/wp2017/lingouta/',
    year: 2017,
  },
  {
    course: 'web programming',
    description: '結合室內設計規劃以及社群的功能，讓模擬居家擺設不再是件難事，輕鬆動動手指，自由的改變房間大小以及家具樣式，同時結合社群的社區模式，分享自己的設計並從他人的作品得到啟發，Open Building 讓設計化為簡單的指尖躍動。',
    english_description: 'Open Building is an easy and free service to build your dream house in 3D. You can resize the room to any shape in any inches. Also, you can take different furniture in variety textures to decorate the space. Share your excellent work and enjoy other fabulous designs around the world in the design community! Be your own interior designer and join us.',
    image: './bg/open-building.jpg',
    image: `https://source.unsplash.com/collection/204/${imageSize}`,
    members: ['雷承勳', '李泓哲', '林京樺', '林政毅', '張友誠'],
    semester: 'fall',
    title: 'Open Building',
    url: 'http://merry.ee.ncku.edu.tw/wp2017/OpenBuilding/',
    year: 2017,
  },
  {
    course: 'web programming',
    description: '【超級多瑪利歐】是一款即時多人連線的網頁遊戲，操縱中年大叔主角瑪利歐與其他玩家展開爭奪終點的廝殺戰！過程中除了要防止其他玩家的攻擊，還會有各式各樣的怪物阻礙前進，所以請撿起地圖上可愛的小道具，努力朝著終點前進吧！',
    english_description: '"Super Marios" is a web realtime MMOG (Massively Multiplayer Online Game) using Mario to take on an exciting adventure. Other real world Marios will attack you from EVERYWHERE.Also, there are monsters blocking your way! No matter what comes to you, just remember, Accessories will always be there to your assistence. Strive for the one and only glory!',
    image: './bg/super-marios.jpg',
    image: `https://source.unsplash.com/collection/205/${imageSize}`,
    members: ['周子軒', '陳哲瑋', '曾大瑋', '段亞培', '黃瀉辰'],
    semester: 'fall',
    title: 'Super Marios',
    url: 'http://merry.ee.ncku.edu.tw/wp2017/SuperMarios/',
    year: 2017,
  },
  {
    course: 'web programming',
    description: '我們提供了如文字編輯器般簡潔易懂的操作模式，讓您可以隨手製作自己的五線譜。您也可以將樂譜存檔在雲端，即可在任何地方輕鬆編輯。還有播放、產生音檔、和弦工具等便利功能，讓作曲效率提升!',
    english_descroption: 'We provided a text-editor-like interface, which enables you to make your own sheet music with no effort. You can access your sheet anytime once you save it on the cloud. Plenty of convenient tools including playing online, generating midi file, chord snippets are here to help you as well!',
    image: './bg/music-sheet-online-editor.jpg',
    image: `https://source.unsplash.com/collection/206/${imageSize}`,
    members: ['顏廷安', '吳岳高', '何奕萱', '林子傑'],
    semester: 'fall',
    title: 'Music Sheet Online Editor',
    url: 'https://msoe.herokuapp.com',
    year: 2016,
  },
  // {
  //   course: 'UIDD2018',
  //   description: '使用者將化身為一隻貓咪，在地圖中恣意探索 在景點內互動對話，蒐集道具史料以了解完整故事，且讓我們跟著貓咪們的腳步認識台南，一起評價吐槽世俗的塵囂吧~',
  //   english_descroption: 'The users will become CATs, explore the map without restraint and have a conversation with the guys they met in the story. By collecting properties during the game, users can recognize the history and the characteristic in Tainan city. Let’s follow the cats’ steps to know more about this lovely city, Tainan! ~',
  //   members: ['劉雨潔', '謝宗霖', '鍾佳熙', '張宇劭', '吳俊德', '潘星羽', '李志諺'],
  //   title: '朕以為人類都是奇葩喵',
  // },
  // {
  //   course: 'UIDD2018',
  //   description: '發想自最近微信上快速竄紅的小遊戲跳一跳，這個遊戲因為玩法簡單，耗時短且能和社群作結合而吸引大量上班族、學生族。我們想將這個遊戲取代傳統大富翁的「執骰子」的動作，讓遊戲不再是那麼益智、耗腦，而是以簡單的風格像是真的在路上跳一跳一樣逛遍台南、了解台南。',
  //   english_description: 'This game is come up with from the mini game being famous rapidly on Wechat recently-"Tiao Yi Tiao". Because of easy to get on track, little time spent, and combining to social media, "Tiao Yi Tiao" attracts lots of office workers and students. We want to replace the movement of "rolling dices" of traditional Millionaire boarding games by the game type of "Tiao Yi Tiao", in order to make the procedure not so puzzling or brainbusting. Instead, users will play within a simple style, but truly like "jumping" on the streets to have a voyage in Tainan!',
  //   members: ['莊銘倫', '王士齊', '譚永勝', '許裕民', '吳宣甫', '陳映帆', '高振鴻'],
  //   title: '跳踏Provintia',
  // },
]

// vi:et:sw=2:ts=2
